SESSION_ID_LABEL_LEN: int

def plain(text: str) -> str: ...
def title_words(name: str | None, n: int = 3) -> str: ...
def format_body(text: str) -> str: ...
def session_block(phrase: str, sid: str | None, title: str | None, body: str | None = None, extra: str | None = None) -> str: ...
