from . import binaries as binaries, ocstore as ocstore

RECENT_DAYS: int
SHORTLIST: int

def metadata() -> dict: ...
def efforts(model_id: str) -> list[str]: ...
def context_window(model_id: str) -> int | None: ...
def model_ids() -> list[str]: ...
def groups() -> dict[str, list[str]]: ...
def favourites() -> list[str]: ...
