from . import answer as answer, reply as reply
from .htmlsplit import split_html as split_html

async def land(live, block: str, markup=None) -> list: ...
async def stamp(live, total: int) -> None: ...
