from . import choices as choices, config as config, labels as labels, msgmap as msgmap, panelmenu as panelmenu, registry as registry

def apply(scope: str, dim: str, value: str) -> str: ...
async def handle_callback(update, context) -> None: ...
