from . import answer as answer, ask as ask, config as config, dispatch as dispatch, format as format, msgmap as msgmap, painter as painter, panelmenu as panelmenu, phrases as phrases, registry as registry, reply as reply, speech as speech, tts as tts, helpers as helpers
from _typeshed import Incomplete

WORKSPACE_DIR: Incomplete
SPOKEN_CHARS: int
RETRIES: int
RETRY_BACKOFF: float

async def guarded(coro, msg) -> None: ...
async def run_and_deliver(msg, working, prompt: str, *, session_id: str | None, backend_name: str, title: str | None, scope: str, spoken: bool = False, lead: str = '') -> None: ...
async def start_new(msg, prompt: str, *, spoken: bool = False, working=None) -> None: ...
async def handle_reply_continue(msg, sid: str, text: str, *, spoken: bool = False, working=None) -> None: ...
